# Generated by Django 2.2.6 on 2022-04-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20220405_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='task title')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='task description')),
                ('task_time', models.IntegerField(verbose_name='task timing')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_tasks', to='program.Program')),
            ],
        ),
    ]
