# Generated by Django 2.2.6 on 2022-04-07 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0003_programtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programtask',
            name='task_time',
            field=models.IntegerField(verbose_name='task timing (in Minutes)'),
        ),
        migrations.CreateModel(
            name='ActionTaskUserProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('status', models.TextField()),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_program_id', to='program.Program')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_task', to='program.ProgramTask')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'program', 'task')},
            },
        ),
    ]
