# Generated by Django 2.2.6 on 2022-04-08 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_auto_20220408_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('icon_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LevelTrackerValueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('unit', models.TextField()),
                ('initial_value', models.IntegerField()),
                ('level_tracker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_tracker_value', to='program.LevelTracker')),
            ],
        ),
        migrations.CreateModel(
            name='LevelTrackerTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('level_tracker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_tracker_tag', to='program.LevelTracker')),
            ],
        ),
    ]
