# Generated by Django 2.2.6 on 2022-04-08 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_leveltracker_leveltrackertag_leveltrackervaluetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveltracker',
            name='icon_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leveltracker',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='leveltrackertag',
            name='tag',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leveltrackervaluetype',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leveltrackervaluetype',
            name='unit',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ProgramLevelTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_tracker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_tracker_program', to='program.LevelTracker')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_level_tracker', to='program.Program')),
            ],
        ),
    ]
