# Generated by Django 2.2.6 on 2022-04-08 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_auto_20220408_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramLevelValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('level_tracker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_tracker_value_program', to='program.LevelTracker')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_level_value_tracker', to='program.Program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramLevelValueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('program_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_level_value', to='program.ProgramLevelValue')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_level_value_type_tag', to='program.LevelTrackerTag')),
                ('value_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_level_value_type', to='program.LevelTrackerValueType')),
            ],
        ),
    ]
