# Generated by Django 2.2.6 on 2022-04-08 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_programlevelvalue_programlevelvaluetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programlevelvaluetype',
            name='tag',
        ),
        migrations.AddField(
            model_name='programlevelvalue',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_level_value_type_tag', to='program.LevelTrackerTag'),
        ),
    ]
