# Generated by Django 2.2.6 on 2022-04-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_programlevelvalue_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveltrackervaluetype',
            name='initial_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programlevelvalue',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
