# Generated by Django 2.2.6 on 2022-04-11 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_auto_20220409_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
            ],
        ),
        migrations.AlterField(
            model_name='programbatchsession',
            name='programBatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs_batch_sessions', to='program.ProgramBatch'),
        ),
        migrations.CreateModel(
            name='ProgramSymptomTrackerValueDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_symptom_tracker_value_date', to='program.Program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramSymptomTrackerValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('program_symptom_tracker_value_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_symptom_tracker_value_date', to='program.ProgramSymptomTrackerValueDate')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramSymptomTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_symptom_tracker', to='program.Program')),
                ('symptom_tracker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptom_tracker_program', to='program.SymptomTracker')),
            ],
            options={
                'unique_together': {('program', 'symptom_tracker')},
            },
        ),
    ]
