# Generated by Django 2.2.6 on 2022-04-11 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0016_programsymptomtrackervaluedate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsymptomtrackervalue',
            name='symptom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptom_tracker_program_value', to='program.SymptomTracker'),
        ),
    ]
