# Generated by Django 2.2.6 on 2022-04-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0017_programsymptomtrackervalue_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsymptomtrackervaluedate',
            name='frequency',
            field=models.CharField(default='Daily', max_length=100),
        ),
    ]
