# Generated by Django 2.2.6 on 2022-04-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0018_programsymptomtrackervaluedate_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsymptomtrackervaluedate',
            name='frequency',
            field=models.CharField(max_length=100),
        ),
    ]
