# Generated by Django 2.2.6 on 2022-04-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0019_auto_20220411_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programbatchsession',
            name='end_time',
            field=models.TimeField(verbose_name='session end time'),
        ),
        migrations.AlterUniqueTogether(
            name='actiontaskuserprogram',
            unique_together=set(),
        ),
    ]
