# Generated by Django 2.2.6 on 2022-04-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0020_auto_20220416_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='programbatch',
            name='capacity',
            field=models.IntegerField(default=2),
        ),
    ]
