# Generated by Django 2.2.6 on 2022-04-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0021_programbatch_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='programbatch',
            name='additional_days',
            field=models.IntegerField(default=2),
        ),
    ]
