# Generated by Django 2.2.6 on 2022-04-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0023_program_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='programbatch',
            name='additional_start_date',
            field=models.DateField(null=True),
        ),
    ]
