# Generated by Django 2.2.6 on 2022-12-29 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0024_programbatch_additional_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='program_review')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Program')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='youtube_video_link',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
