# Generated by Django 2.2.6 on 2022-12-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0027_auto_20221230_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='files',
        ),
        migrations.AddField(
            model_name='reviewfiles',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Review'),
        ),
    ]
