FROM python:3.8.0-buster
LABEL maintainer "OPSKUBE"

RUN apt update -y && apt install -y bash python3-tk ghostscript libgl1-mesa-dev

ENV  ENV=prod
ENV  TZ=Asia/Kolkata
ENV  PYTHONDONTWRITEBYTECODE=1


COPY . app/
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN python manage.py makemigrations
RUN python manage.py migrate

CMD python -u manage.py collectstatic
