# Generated by Django 2.2.6 on 2022-04-05 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('resource_file_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='actual doc file url')),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='field to upload file')),
                ('keywords', models.TextField(blank=True, null=True)),
                ('html_body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='resource aaded at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='resource updaated at')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='mdeia description')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='temporary field for getting file from admin panel')),
                ('file_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='actual doc file url')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='session creation date')),
                ('last_modified_timestamp', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_uploaded_by_user', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_last_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
