from django.urls import path
from django.conf.urls import url
from .views import *

urlpatterns = [
    path('get-program/', ProgramList.as_view(),name="Program list"),
    path('search-programs/', SearchProgramList.as_view(),name="Search Program list"),
    path('my-program/', MyPrograms.as_view(),name="for current user subcribed program list"),
    path('expert-programs/<expert_id>/', ExpertPrograms.as_view(),name="for current user subcribed program list"),
    path('program-details/<batch_id>/', ProgramDetails.as_view(), name='Program Details'),
    path('create-program-user/', CreateProgramBatchUser.as_view(), name='Create program user'),
    path('get-program-user/', GetProgramBatchUser.as_view(), name='Getting program user'),
    path('add-favorite-program/', AddFavoriteProgarm.as_view(), name='Create program user'),
    path('remove-favorite-program/', RemoveFavoriteProgram.as_view(), name='delete program from user favorite list'),
    path('get-favorite-program/', FavoriteProgramsList.as_view(),name="favoritr Programs list"),
    path('get-program-batch-session-resources/<programBatchSession_id>/', GetProgramBatchSessionResources.as_view(),name="get program batch session resources"),
    path('start-program-batch-session/<programBatchSession_id>', UpdateProgramBatchSessionDateTime.as_view()),
    path('get-filter-program/', GlobalSearchProgram.as_view(),name="program global search"),
    path('user-payment-detail', UserPaymentDetailCreate.as_view(), name = "user payment detail"),
    path('user-payment-upload', UserPaymentDetailUpload.as_view(), name="paymet screen short upload"),
    path('user-payment-razorpay', UserPaymentRazorPay.as_view(), name="razorpay data add"),
    path('apply_discount/', ApplyDiscount.as_view(), name='apply_discount'),
    path('upsert_task_action/', AddTaskActionTask.as_view(), name='upsert_task_action'),
    path('add_level_tracker_value/', AddLevelTrackerValue.as_view(), name='add_level_tracker_value'),
    path('get_level_tracker_value/<program>/<level_tracker>/<tag>/<days>/', GetLevelTrackerValue.as_view(), name='get_level_tracker_value'),
    path('remove_level_tracker_value/', RemoveLevelTrackerValue.as_view(), name='remove_level_tracker_value'),
    path('add_symptom_tracker_value/', AddSymptomTrackerValue.as_view(), name='add_symptom_tracker_value'),
    path('get_symptom_tracker_value/<program>/<days>/', GetSymptomTrackerValue.as_view(), name='get_symptom_tracker_value'),
    path('remove_symptom_tracker_value/', RemoveSymptomTrackerValue.as_view(), name='remove_symptom_tracker_value'),
    path('get_actions_datewise/<program_id>/<dt_low>/<dt_high>/', GetActionsDatewise.as_view(),
         name='get_actions_datewise'),

    path('get-program-categorywise', ProgramCategoryWiseList.as_view(), name="get program category wise list"),
    path('upcoming-programs',UpcomingPrograms.as_view(),name="upcoming programs"),
    path('expert-all-program',ExpertAllPrograms.as_view(),name="expert all programs"),
    path('expert-upcoming-session',ExpertUpcomingSession.as_view(),name='expert upcoming sessions'),
    path('expert-program-batch-details/<batch_id>',ExpertProgramBatchDetails.as_view(),name="expert program batch details"),
    path('update-expert-program-batch-details', ExpertProgramBatchDetails.as_view(),
         name="expert program batch details"),
    path('app-program-batch-details/<batch_id>',ExpertAppProgramDetails.as_view(),name="expert app program batch details"),
    path('program-listing',ProgramListing.as_view(),name="program listing"),
    path('favourite-program-list',ProgramFavoriteList.as_view(),name="favourite program list"),
    path('add-review',ProgramReview.as_view(),name="add review"),
    path('review-list/<program_id>',ReviewList.as_view(),name="review list"),
    path('add-review-like/<review_id>',ReviewLike.as_view(),name="add review like"),
    path('remove-review-like/<review_id>',ReviewLike.as_view(),name="remove review like"),
]
