# Generated by Django 2.2.6 on 2022-07-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220416_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('timezone_id', models.AutoField(primary_key=True, serialize=False)),
                ('timezone_name', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
    ]
