# Generated by Django 2.2.6 on 2022-07-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220730_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('expertise_id', models.AutoField(primary_key=True, serialize=False)),
                ('expertise_name', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='experties',
        ),
        migrations.AddField(
            model_name='user',
            name='experties',
            field=models.ManyToManyField(blank=True, null=True, related_name='expertise', to='user.Expertise'),
        ),
    ]
