# Generated by Django 2.2.6 on 2022-08-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220803_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertteammember',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expertteammember',
            name='phone',
            field=models.CharField(help_text='Phone number of user', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('customer', 'Customer'), ('expert', 'Expert'), ('teammember', 'Team Member')], default='customer', max_length=100),
        ),
    ]
