# Generated by Django 2.2.6 on 2022-08-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220808_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeCertification',
            fields=[
                ('degree_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),

        migrations.AddField(
            model_name='usereducationdetail',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DegreeCertification', to='user.DegreeCertification'),
        ),
    ]
