# Generated by Django 2.2.6 on 2022-08-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20220816_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertteammember',
            name='is_active',
            field=models.BooleanField(default=False),
        )

    ]
