# Generated by Django 2.2.6 on 2022-09-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20220816_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertteammember',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expertteammember',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number of user', max_length=15, null=True),
        ),
    ]
