# Generated by Django 2.2.6 on 2022-04-30 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupcategory',
            options={'verbose_name': 'Group Category'},
        ),
        migrations.AddField(
            model_name='group',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
