# Generated by Django 2.2.6 on 2022-04-30 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_groupinvited_groupmembers_grouprequested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinvited',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_invited_group', to='group.Group'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_group', to='group.Group'),
        ),
        migrations.AlterField(
            model_name='grouprequested',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_requested_group', to='group.Group'),
        ),
    ]
