# Generated by Django 2.2.6 on 2022-04-30 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20220430_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvited',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=60),
        ),
        migrations.AddField(
            model_name='groupinvited',
            name='status_modified_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='grouprequested',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=60),
        ),
        migrations.AddField(
            model_name='grouprequested',
            name='status_modified_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='group',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('public', 'Private')], default='public', max_length=60),
        ),
    ]
