# Generated by Django 2.2.6 on 2022-04-30 23:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0005_auto_20220430_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cover_image',
            field=models.FileField(default='a', upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(default=datetime.datetime.now)),
                ('approved_on', models.DateTimeField(default=datetime.datetime.now)),
                ('text', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_post_approved_by', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_post_group', to='group.Group')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_post_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
