# Generated by Django 2.2.6 on 2022-04-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20220430_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppost',
            old_name='approved_on',
            new_name='status_modified_on',
        ),
        migrations.AddField(
            model_name='grouppost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=60),
        ),
    ]
