# Generated by Django 2.2.6 on 2022-04-30 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_auto_20220430_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppost',
            old_name='approved_by',
            new_name='status_changed_by',
        ),
    ]
