# Generated by Django 2.2.6 on 2022-05-01 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20220501_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPostMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=4000)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_media_post_group', to='group.GroupPost')),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=60),
        ),
        migrations.DeleteModel(
            name='GroupMedia',
        ),
    ]
