# Generated by Django 2.2.6 on 2022-05-03 23:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0011_grouprequested_status_modified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(default=datetime.datetime.now)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_post_like_member', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_post_like_post', to='group.GroupPost')),
            ],
            options={
                'unique_together': {('post', 'member')},
            },
        ),
    ]
