# Generated by Django 2.2.6 on 2022-05-09 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_grouppostlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='category',
        ),
        migrations.CreateModel(
            name='GroupCategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ggroup_group_category', to='group.GroupCategory')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ggroup_invited_group', to='group.Group')),
            ],
        ),
    ]
