# Generated by Django 2.2.6 on 2022-05-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0013_auto_20220509_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='post_mode',
            field=models.CharField(choices=[('admin', 'Admin'), ('members', 'Members')], default='admin', max_length=60),
        ),
    ]
