# Generated by Django 2.2.6 on 2022-05-11 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_group_post_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvited',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
