# Generated by Django 2.2.6 on 2022-05-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_groupinvited_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='approved', max_length=60),
        ),
    ]
