# Generated by Django 2.2.6 on 2022-05-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0017_groupadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('removed', 'Removed')], default='approved', max_length=60),
        ),
        migrations.AlterField(
            model_name='groupinvited',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('removed', 'Removed')], default='pending', max_length=60),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('removed', 'Removed')], default='approved', max_length=60),
        ),
        migrations.AlterField(
            model_name='grouprequested',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('removed', 'Removed')], default='pending', max_length=60),
        ),
    ]
