# Generated by Django 2.2.6 on 2022-07-02 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0020_auto_20220605_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 4, 51, 2, 816538)),
        ),
    ]
