# Generated by Django 2.2.6 on 2022-07-29 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0021_auto_20220702_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 18, 41, 45, 445368)),
        ),
    ]
