# Generated by Django 2.2.6 on 2022-07-29 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0022_auto_20220729_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 19, 8, 21, 442578)),
        ),
    ]
