# Generated by Django 2.2.6 on 2022-07-30 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0025_auto_20220730_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 16, 45, 39, 438797)),
        ),
    ]
