# Generated by Django 2.2.6 on 2022-08-03 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0030_auto_20220801_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 18, 48, 4, 922375)),
        ),
    ]
