# Generated by Django 2.2.6 on 2022-08-08 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0032_auto_20220808_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 13, 48, 28, 514353)),
        ),
    ]
