# Generated by Django 2.2.6 on 2022-08-16 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0034_auto_20220808_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 13, 49, 6, 224238)),
        ),
    ]
