# Generated by Django 2.2.6 on 2022-08-16 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0035_auto_20220816_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 16, 4, 53, 459609)),
        ),
    ]
