# Generated by Django 2.2.6 on 2022-09-15 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0036_auto_20220816_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 13, 15, 49, 93100)),
        ),
    ]
