# Generated by Django 2.2.6 on 2022-09-15 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0038_auto_20220915_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 13, 44, 15, 95099)),
        ),
    ]
