# Generated by Django 2.2.6 on 2022-10-11 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0040_auto_20220915_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 13, 57, 55, 4191)),
        ),
    ]
