# Generated by Django 2.2.6 on 2022-10-20 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0041_auto_20221011_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 16, 53, 10, 97523)),
        ),
    ]
