# Generated by Django 2.2.6 on 2022-10-28 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0044_auto_20221026_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 16, 31, 38, 83259)),
        ),
    ]
