# Generated by Django 2.2.6 on 2022-11-08 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0045_auto_20221028_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 17, 22, 39, 350832)),
        ),
    ]
