# Generated by Django 2.2.6 on 2022-11-28 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0046_auto_20221108_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 17, 47, 42, 88994)),
        ),
    ]
