# Generated by Django 2.2.6 on 2022-12-26 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0048_auto_20221129_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 17, 18, 22, 873734)),
        ),
    ]
