# Generated by Django 2.2.6 on 2022-12-30 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0051_auto_20221229_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 13, 41, 41, 91319)),
        ),
    ]
