# Generated by Django 2.2.6 on 2022-12-30 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0053_auto_20221230_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 15, 28, 17, 696404)),
        ),
    ]
