# Generated by Django 2.2.6 on 2022-10-11 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220405_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Only jpeg,jpg and png allowed')]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('requested', 'REQUESTED'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('published', 'PUBLISHED'), ('under_review', 'UNDER_REVIEW')], default='draft', max_length=20),
        ),
    ]
