# Generated by Django 2.2.6 on 2022-10-20 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221011_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='banner_image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Actual Banner Image Url'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='feature_image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Actual Feature Image Url'),
        ),
    ]
