# Generated by Django 2.2.6 on 2022-11-28 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20221020_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='favourite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite_blog', to=settings.AUTH_USER_MODEL),
        ),
    ]
