# Generated by Django 2.2.6 on 2022-10-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20220915_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('requested', 'REQUESTED'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('published', 'PUBLISHED'), ('under_review', 'UNDER_REVIEW')], default='draft', max_length=20),
        ),
    ]
