# Generated by Django 2.2.6 on 2022-04-05 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100, null=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('slug', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=300, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('video_link', models.CharField(max_length=200, null=True)),
                ('thumbnail_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='temporary field for getting file from admin panel')),
                ('thumbnail_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='actual s3 file url')),
                ('description', models.TextField(help_text='Min. 150 character', null=True)),
                ('webinar_date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('whatsapp_link', models.CharField(blank=True, max_length=200, null=True)),
                ('blue_bird_email_template_id', models.CharField(default='108', max_length=5, null=True)),
                ('displayOrder', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=100)),
                ('createdAt', models.DateField(auto_now_add=True, verbose_name='created date')),
            ],
            options={
                'ordering': ['-webinar_date'],
            },
        ),
        migrations.CreateModel(
            name='WebinarSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overiddenContent', models.TextField(blank=True, null=True)),
                ('displayOrder', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webinar.Section')),
                ('webinar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webinar.Webinar')),
            ],
            options={
                'ordering': ['displayOrder'],
            },
        ),
        migrations.CreateModel(
            name='WebinarCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_category', to='user.Category')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_for_category', to='webinar.Webinar')),
            ],
            options={
                'unique_together': {('webinar', 'category')},
            },
        ),
        migrations.AddField(
            model_name='webinar',
            name='category',
            field=models.ManyToManyField(related_name='webinar_categories', through='webinar.WebinarCategory', to='user.Category'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WebinarSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_mobile_no', models.CharField(max_length=100)),
                ('subscriptionDatetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('Attended', 'Attended'), ('Not Attended', 'Not Attended')], max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webinar.Webinar')),
            ],
            options={
                'unique_together': {('whatsapp_mobile_no', 'webinar')},
            },
        ),
    ]
