# Generated by Django 2.2.6 on 2022-10-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_query_program_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='querycomment',
            old_name='query_id',
            new_name='query',
        ),
        migrations.RenameField(
            model_name='querycommentreply',
            old_name='comment_id',
            new_name='comment',
        ),
    ]
